package org.jozif.articleFetcher.entity;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ID
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ARTICLE_ID
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ARTICLE_NAME
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ARTICLE_URL
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String articleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.HTML_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String htmlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.SCREENSHOT_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String screenshotPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.PDF_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String pdfPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.PLATFORM
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.WORD_COUNT
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private Integer wordCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.REMARK
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.GMT_REAL
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private Date gmtReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.GMT_CREATE
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CONTENT
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ID
     *
     * @return the value of article.ID
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ID
     *
     * @param id the value for article.ID
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ARTICLE_ID
     *
     * @return the value of article.ARTICLE_ID
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ARTICLE_ID
     *
     * @param articleId the value for article.ARTICLE_ID
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ARTICLE_NAME
     *
     * @return the value of article.ARTICLE_NAME
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ARTICLE_NAME
     *
     * @param articleName the value for article.ARTICLE_NAME
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ARTICLE_URL
     *
     * @return the value of article.ARTICLE_URL
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getArticleUrl() {
        return articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ARTICLE_URL
     *
     * @param articleUrl the value for article.ARTICLE_URL
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.HTML_PATH
     *
     * @return the value of article.HTML_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getHtmlPath() {
        return htmlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.HTML_PATH
     *
     * @param htmlPath the value for article.HTML_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setHtmlPath(String htmlPath) {
        this.htmlPath = htmlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.SCREENSHOT_PATH
     *
     * @return the value of article.SCREENSHOT_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getScreenshotPath() {
        return screenshotPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.SCREENSHOT_PATH
     *
     * @param screenshotPath the value for article.SCREENSHOT_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setScreenshotPath(String screenshotPath) {
        this.screenshotPath = screenshotPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.PDF_PATH
     *
     * @return the value of article.PDF_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getPdfPath() {
        return pdfPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.PDF_PATH
     *
     * @param pdfPath the value for article.PDF_PATH
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setPdfPath(String pdfPath) {
        this.pdfPath = pdfPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.PLATFORM
     *
     * @return the value of article.PLATFORM
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.PLATFORM
     *
     * @param platform the value for article.PLATFORM
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.WORD_COUNT
     *
     * @return the value of article.WORD_COUNT
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public Integer getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.WORD_COUNT
     *
     * @param wordCount the value for article.WORD_COUNT
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setWordCount(Integer wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.REMARK
     *
     * @return the value of article.REMARK
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.REMARK
     *
     * @param remark the value for article.REMARK
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.GMT_REAL
     *
     * @return the value of article.GMT_REAL
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public Date getGmtReal() {
        return gmtReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.GMT_REAL
     *
     * @param gmtReal the value for article.GMT_REAL
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setGmtReal(Date gmtReal) {
        this.gmtReal = gmtReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.GMT_CREATE
     *
     * @return the value of article.GMT_CREATE
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.GMT_CREATE
     *
     * @param gmtCreate the value for article.GMT_CREATE
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CONTENT
     *
     * @return the value of article.CONTENT
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CONTENT
     *
     * @param content the value for article.CONTENT
     *
     * @mbggenerated Fri Aug 24 14:05:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        return "Article{" +
                "id=" + id +
                ", articleId='" + articleId + '\'' +
                ", articleName='" + articleName + '\'' +
                ", articleUrl='" + articleUrl + '\'' +
                ", htmlPath='" + htmlPath + '\'' +
                ", screenshotPath='" + screenshotPath + '\'' +
                ", pdfPath='" + pdfPath + '\'' +
                ", platform='" + platform + '\'' +
                ", wordCount=" + wordCount +
                ", remark='" + remark + '\'' +
                ", gmtReal=" + gmtReal +
                ", gmtCreate=" + gmtCreate +
                ", content='" + content + '\'' +
                '}';
    }
}