#=================================================================================

spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=TRUE;DB_CLOSE_DELAY=-1

    driverClass: org.h2.Driver
    username: demo
    password: 941021
    platform: h2
    schema: classpath:/h2sql/schema-h2.sql
    data: classpath:/h2sql/data-h2.sql
    initialize: true
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
