server:
  port: 41021


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.jozif.demo4mybatis.entity

#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:logback.xml

spring:
  profiles:
    active: 'h2'
#    active: 'dev'