CREATE TABLE `USER` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(63)  NOT NULL,
  `PASSWORD` varchar(255)  NOT NULL,
  `SALT` varchar(255) NOT NULL,
  `EMAIL` varchar(127) NOT NULL,
  `CELL_PHONE` varchar(63)  DEFAULT NULL,
  `WECHAT_OPEN_ID` varchar(255) DEFAULT NULL,
  `ROLE` int(11) DEFAULT NULL,
  `DEPARTMENT` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `GMT_CREATE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `GMT_LAST_UPDATE` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `GMT_LAST_LOGIN` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);