package org.jozif.demo4mybatis.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SALT
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CELL_PHONE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private String cellPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ROLE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DEPARTMENT
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private Integer department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATUS
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.GMT_CREATE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.GMT_LAST_LOGIN
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    private Date gmtLastLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SALT
     *
     * @return the value of user.SALT
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SALT
     *
     * @param salt the value for user.SALT
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CELL_PHONE
     *
     * @return the value of user.CELL_PHONE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CELL_PHONE
     *
     * @param cellPhone the value for user.CELL_PHONE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ROLE
     *
     * @return the value of user.ROLE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ROLE
     *
     * @param role the value for user.ROLE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DEPARTMENT
     *
     * @return the value of user.DEPARTMENT
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DEPARTMENT
     *
     * @param department the value for user.DEPARTMENT
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATUS
     *
     * @return the value of user.STATUS
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATUS
     *
     * @param status the value for user.STATUS
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.GMT_CREATE
     *
     * @return the value of user.GMT_CREATE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.GMT_CREATE
     *
     * @param gmtCreate the value for user.GMT_CREATE
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.GMT_LAST_LOGIN
     *
     * @return the value of user.GMT_LAST_LOGIN
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public Date getGmtLastLogin() {
        return gmtLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.GMT_LAST_LOGIN
     *
     * @param gmtLastLogin the value for user.GMT_LAST_LOGIN
     *
     * @mbggenerated Wed Jan 31 14:44:03 CST 2018
     */
    public void setGmtLastLogin(Date gmtLastLogin) {
        this.gmtLastLogin = gmtLastLogin;
    }
}